### ISSUE TITLE
flatpak app doesn't lauch

### ISSUE THREAD

**Issue by eriolloan** [Unrud/recent-filter#5]
I'm getting this every time I try to launch :

```
$ flatpak run -v io.github.unrud.RecentFilter

F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/user/.local/share/flatpak
F: Opening user flatpak installation at path /home/user/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Skipping parental controls check for app/io.github.unrud.RecentFilter/x86_64/stable since parental controls are disabled globally
F: Opening user flatpak installation at path /home/user/.local/share/flatpak
F: /home/user/.local/share/flatpak/runtime/org.gnome.Platform/x86_64/44/af9771528c16267ff974784890b39714541fa093adaea0a2bf26bfdbc586d4fd/files/lib32 does not exist
F: Allocated instance id 2286599621
F: Add defaults in dir /io/github/unrud/RecentFilter/
F: Add locks in dir /io/github/unrud/RecentFilter/
F: Disallowing network access
F: Allowing dri access
F: Allowing homedir access
F: Allowing wayland access
F: Running 'bwrap --args 38 xdg-dbus-proxy --args=40'
F: Running 'bwrap --args 38 recent-filter'

Traceback (most recent call last):
  File "/app/bin/recent-filter", line 51, in <module>
    sys.exit(main.main(VERSION))
  File "/app/share/recent-filter/recent_filter/main.py", line 70, in main
    app = RecentFilterApplication()
  File "/app/share/recent-filter/recent_filter/main.py", line 39, in __init__
    self.service = gobject_log(Service(self))
  File "/app/share/recent-filter/recent_filter/service.py", line 53, in __init__
    self._cs.push(PropertyBinding(
  File "/app/share/recent-filter/recent_filter/util/connection.py", line 115, in __init__
    self.__apply(obj_a, prop_a, obj_b, prop_b, func_a_to_b)
  File "/app/share/recent-filter/recent_filter/util/connection.py", line 122, in __apply
    value = to_func(value)
  File "/app/share/recent-filter/recent_filter/service.py", line 75, in _on_active_changed
    self._bg_portal.set_status(N_('Service deactivated'))
  File "/app/share/recent-filter/recent_filter/background_portal.py", line 67, in set_status
    self._background_proxy.call_sync(
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Method « SetStatus » does not exist (19)

```

The application never worked after installing.

RecentFilter is up-to-date (0.1.3)

Flatpak is 1.14.0, the latest version available I can get on my distro. Probably not a factor (current version is only 1.14.5).

Vanilla OS 22.10 Kinetic

Hope this bug report helps you.

**Comment by Unrud** [comment]
It fails because the version of **xdg-desktop-portal** is too old.
